/**
 * folder-images.js — auto-load the first image found in each per-slot folder.
 *
 * Drop ANY image (jpg/jpeg/png/webp/avif/gif) into images/<slot-id>/ and it
 * shows up in the matching <image-slot> automatically — no HTML editing needed.
 *
 * How it finds the image, in order:
 *   1) images/manifest.json — a build-time index of every folder's files.
 *      This is the reliable path on Netlify (and any static host): commit your
 *      image + the manifest (regenerated by generate-manifest.js, run by the
 *      Netlify build) and the picture is permanent across refreshes/devices.
 *   2) Apache/XAMPP directory listing — for live local editing without a build:
 *      scrape the auto-generated index for the first image link.
 *   3) Common-name fallback — try predictable names (1.jpg, photo.png, ...).
 *
 * A user drag-drop onto a slot (image-slot.js sidecar) still wins where that
 * works; otherwise this fills the slot by setting its `src` attribute, which
 * image-slot.js treats as the initial/fallback image.
 */
(() => {
  const FOLDER = 'images';
  const MANIFEST_URL = FOLDER + '/manifest.json';
  const EXTS = ['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'];
  const FALLBACK_BASENAMES = ['1', 'photo', 'cover', 'main', 'img', 'image'];
  const IMG_RE = /\.(jpe?g|png|webp|avif|gif)(?:\?.*)?$/i;

  // 1) Build-time manifest — the only fully reliable source on static hosts.
  async function loadManifest() {
    try {
      const res = await fetch(MANIFEST_URL, { cache: 'no-store' });
      if (!res.ok) return null;
      const json = await res.json();
      return json && typeof json === 'object' ? json : null;
    } catch (_) {
      return null;
    }
  }

  // 2) Apache (or similar) auto-index page — scrape the first image href.
  async function fromDirectoryListing(dir) {
    try {
      const res = await fetch(dir + '/', { cache: 'no-store' });
      if (!res.ok) return null;
      const ct = res.headers.get('content-type') || '';
      if (!ct.includes('text/html')) return null;
      const html = await res.text();
      const doc = new DOMParser().parseFromString(html, 'text/html');
      const links = Array.from(doc.querySelectorAll('a[href]'));
      for (const a of links) {
        const href = a.getAttribute('href') || '';
        if (href.startsWith('?') || href.startsWith('/') || href.includes('..')) continue;
        if (IMG_RE.test(href)) return dir + '/' + href.split('/').pop();
      }
    } catch (_) {}
    return null;
  }

  function exists(url) {
    return fetch(url, { method: 'HEAD', cache: 'no-store' })
      .then((r) => {
        if (!r.ok) return false;
        const ct = r.headers.get('content-type') || '';
        return ct.startsWith('image/') || ct === '';
      })
      .catch(() => false);
  }

  // 3) Predictable filenames, last resort.
  async function fromCommonNames(dir) {
    for (const base of FALLBACK_BASENAMES) {
      for (const ext of EXTS) {
        const url = dir + '/' + base + '.' + ext;
        if (await exists(url)) return url;
      }
    }
    return null;
  }

  async function resolveFor(slot, manifest) {
    const id = slot.id;
    if (!id || slot.getAttribute('src')) return;
    const dir = FOLDER + '/' + id;

    let found = null;
    if (manifest && Array.isArray(manifest[id]) && manifest[id].length) {
      found = dir + '/' + manifest[id][0];
    }
    if (!found) found = await fromDirectoryListing(dir);
    if (!found) found = await fromCommonNames(dir);

    if (found && !slot.getAttribute('src')) slot.setAttribute('src', found);
  }

  async function run() {
    const manifest = await loadManifest();
    const slots = document.querySelectorAll('image-slot[id]');
    slots.forEach((slot) => { resolveFor(slot, manifest); });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', run);
  } else {
    run();
  }
})();
